version: 2
builds:
  - id: sopsv
    binary: sopsv
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    main: ./main.go
    hooks:
      pre: go mod tidy
      post: go mod tidy

checksum:
  # You can change the name of the checksums file.
  #
  # Default: '{{ .ProjectName }}_{{ .Version }}_checksums.txt', or,
  #   when split is set: '{{ .ArtifactName }}.{{ .Algorithm }}'.
  # Templates: allowed.
  name_template: "{{ .ProjectName }}-checksums.txt"

archives:
  - id: sopsv
    formats: [tar.gz]
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}-{{ .Version }}"
    format_overrides:
      - goos: windows
        formats: [zip, tar.gz]

    files:
      - LICENSE.md
      - README.md

nfpms:
  - id: sopsv
    description:  |
      sopsv is a cross platform tool enabling the use of sops and json as a local secret store."
    homepage: "https://github.com/hyprxlabs/xsops"
    file_name_template: "{{ .PackageName }}-{{ .Os }}-{{ .Arch}}-{{ .Version }}"
    maintainer: "Hyprxdev <180069990+hyprxdev@users.noreply.github.com>"
    license: "MIT"
    formats:
      - deb
      - rpm
      - archlinux
      - apk

chocolateys:
  - name: sopsv
    description: |
      A cross-platform tool enabling sops and json as a local secret store.

      The `sopsv` command allows you to manage secrets stored in JSON files using the sops tool.
      The secrets can be easily retrieved, set, and removed from the command line.
    package_source_url: "https://github.com/hyprxlabs/xsops"
    title: "sopsv"
    project_url: "https://github.com/frostyeti/sopsv"
    copyright: "Copyright © 2025 Frostyeti Grimfrost Mage"
    require_license_acceptance: false
    icon_url: "https://raw.githubusercontent.com/frostyeti/presskit/refs/heads/main/assets/logo.png"
    authors: "Hyprxdev <180069990+hyprxdev@users.noreply.github.com>"
    tags: "sopsv sops"
    summary: "sopsv is a crossplatform cli app for sops and json as a local secret store."
    release_notes: "https://github.com/frostyeti/sopsv/releases/tag/v{{ .Version }}"
    skip_publish: true

    